#+title: journal.org
#+setup: num indent 

* <2026-04-10 Fri>

It seems like everything takes so long. I hope there is a [[denote:20260410T065414][UTLA]] strike. My goal is to clear my credential in 10 months and then find something else. The last sentence is one intuition. I regret not finishing my credential when I was at Casa Ramona. I am proud to say that I am a chemistry teacher. I am proud of what I do and I want to get better at it. Maybe I just need to ignore the [[denote:20260306T055322][Olga]]s? Or maybe, I should do the opposite. You can debate whether teaching is an art or a science. 

It is my sister's birthday. I just sent her a text. I am not sure if it went through. 

* <2026-04-07 Tue>

51 today. Start of second week on ozempic. [[denote:20260323T073117][gtd]] has fallen away. I wonder if I would feel more accomplished had I implemented it over the break? I started the [[denote:20260407T065713][hydroponic]] system. My lack of detail orientation had caused me to have to carry 40 pounds of chlorine tablets to my car from the main PACS office. I was struggling and out of breath by the time I got to my car. I realized that I have at least twice that weight distributed over my body that I carry all the time. 

* <2026-04-01 Wed>

Middle of spring break. I have been devoting most of my time to the greenhouse. 


* <2026-03-26 Thu>

Today is really the first day of spring break. [[denote:20260325T074325][koi pond]] progress.

* <2026-03-24 Tue>

First period covered by Yera and met with Dr. B for almost the entire period. Suggested seating chart and observe Tinoco. 

The [[denote:20260324T174139][Matthew Effect]] triggers my bullshit response. This is a moment when it is better to light a candle than curse the darkness.

* <2026-03-23 Mon>

I didn't prepare for today. This weekend was bad. I have been phoning it in all year. The last sentence is reference to work. I want to be working on my koi pond/greenhouse. I have to come here and half-ass it so I can work on my [[denote:20260323T072146][project]]s. 

* <2026-03-17 Tue>

Met with the principal yesterday morning. I listened to an audiobook on teaching on the drive home(well, a few minutes of the drive home... baby steps). Portillo shared that she ([[denote:20260306T055322][Olga]]) observed his advisory. In summary, I am sitting in my classroom and I feel good about my situation. I have to remain vigilant in that that situation can change in a moment.   

* <2026-03-12 Thu>

I think if I enjoyed teaching I would do the prep I need to do. I dread Monday and I live for Friday.I count the days till summer way too early. It's hard doing something you are not good at. It sucks to be new and it sucks to suck at something. It sucks even more, when you have someone randomly and consistently reminding you how much you suck(as a note to my future self, I am talking about a conflict with [[denote:20260306T055322][Olga]] Dubenchuk).

I truly hate this job. The only job I loved was the only job I really lost. I don't think it's coming back.

Today I learned what [[denote:20260312T160909][vibe coding]] is. It's basically the term for the practice that caused me to loose my job at [[denote:20260218T063536][coding dojo]].

* <2026-03-07 Sat>

**  final [[denote:20260307T100916][EGI]] salary point training.
*** passwords
  [[https://tguskey.com/][Guskey]]
  [[https://en.wikipedia.org/wiki/Robert_J._Marzano][Marzano]]

 - "please sir, can I have more points?"

   - switch from points to assess level of knowledge

*** syllabus

- you must grade according to syllabus
- syllabus must be aligned with LAUSD policy



* <2026-03-06 Fri>

- second consecutive absence from work. 
- tentative goal: prep for next week, but also plan an [[denote:20260306T055122][exit strategy]]. 

- from Geometry for Programmers:  
  #+begin_quote
 But software frameworks will come and go, and hardware architecture will evolve; the only thing that will stand the test of time is mathematics.
  #+end_quote

- "paint the back of the fense" - jobs

https://dannysuede.substack.com/p/paint-the-back-of-the-fence

What is the difference between:

- the back of the fence
- under the rug
- in the wall

??

* <2026-03-05 Thu>

Therapy last night. Within the same session I was "doing all that I could" then when the topic of sex arose, I was a free-loading piece-of-shit again. I really want to make this work, but it's not looking good.

I am taking a "mental health day" today. 

* <2026-03-02 Mon>

I complained about the harrasment and it seems to have stopped. I am not sure if the complaint had anything to do with it. I can only speculate. I stay in my room, by my self. I only interact with 15 year olds.

My depression is back. This weekend was one of the worst of my life. I don't know if my marrage will last. It will be 20 years in december, but that doesn't mean anything. Forty-year marrages end.

Maybe I have become weak. 

* <2026-02-27 Fri>

I am filing an age discrimination case against LAUSD. Does the perp of the descrimination have to be a superior? My intuition is that the answer is "no", but I am not certain.

This job, teaching, sucks. One asshole can ruin a job.

* <2026-02-22 Sun>

** thoughts on future goals

I was sitting with Alto on Friday and I counted the days until <2026-06-10 Wed>. I was happier at coding dojo. 

** emacs vs vim

I spent a lot of time messing with vim. Why not just use evil-mode. I read somewhere that evil-mode is a better version of vim then vim. 

* <2026-02-19 Thu>

Less than 60 days from my 51st birthday, 100 pounds over weight, and a pain in my right foot that has been persistent for several months. I am sitting in an outdated, hastily and half-heartedly equipped chemistry classroom in South-Central Los Angeles. I have no idea what I am going to do today. That is not exactly true. 

I have to stay late for a meeting, I think it's student councel. Whatever, my point is, I seem to make entries when I am fucking miserable and now is not an exception.

I am really close to clearing my credential. It would be stupid to walk away from that. And upon reflection, miserable is a strong word. If I am to be honest about what I liked about the job was the very minimal responsibilites. I only taught 2 hours a day!

I really liked programming. It seems I could hone my skills in my "spare time." Learning C and Go and also achieving my goal of getting my math credential.

* <2026-02-18 Wed>

I am sitting in a Chemistry classroom in South Los Angeles on a cold, rainy Febuary morning. Why am I here, in this cold classroom in this sad and wonderful place? I lost my [[denote:20260218T063536][job]]. 

* <2026-02-14 Sat>

Someone asks a senior professor if he would recomend a graduate student for an open professor position at the university. The senior professor responds, "He has very good handwriting." 

Someone asks a man's wife," who would want to have sex with her husband? Look at him." The wife responds, "Prostitutes would."

Happy Vanentine's Day!

* <2026-02-02 Mon>

Doomscrolling. I doomscroll because I am unhappy, I am unhappy because I doomscroll. The last sentence was a joke. For who? It doesn't add substance to what I am writing. I wrote the first two sentences, because I have an issue with spending, what I see as, an excessive amount of time viewing content online that is not productive. 

I have to write for work. I have to write with proper citations. I am very fearful. It seems time invested learning orgmode is not wasted.  

* <2026-01-30 Fri>

Ice-out day. I truly feel responsible for what is happening. Every time I laughed, or even smiled at a racist joke, I help perpetuate facism. Toleration of intolerance is complicity.

I bought a sandwich on the day of protest. I don't sort my garbage. I don't adaquately prepare for teaching my students. Is it because they are brown? Would I behave the same way if I taught at Hart High? In a lot of ways, I am ashamed of my lack of vigilance; my lack of effort.   

* <2026-01-21 Wed>

- I don't want the [[file:autobiography/index.org][autobiography]] to be too detailed or a bitch session about my childhood. I do want to make a through inventory of what has happened and what went wrong. Also what went right. 

- An argument for having a modularized customization for emacs is that there are certain settings that have to be in the init file for emacs to be useful (i.e. the location of agenda files) 

* <2026-01-20 Tue>

Alas, I didn't install [[denote:20260214T192429][R]]. I just edited the previous entry for clarity before starting this one. I have done the same thing in the past.

The idea of a book for my children...What about an autobiography? It seems this would be an exercise for me in metacognition.

* <2026-01-17 Sat>

It seems the information is more important then what date it happened in keeping a journal. Today I have been focused on go and statistics. I feel compelled to install R!

* <2026-01-16 Fri>

What if I wrote a book for my children? What if I recoreded my knowledge for them. 

* <2026-01-14 Wed>

I have to do something about keeping a journal. Sometimes simple is better. This is, as of now, a simple '.org' file called journal.org. A stumbling block for me has been thinking too hard and long about a perfect system. I can't think effectively without writing. So, not keeping a journal seems foolish.

